In [21]:
# Import necessary modules
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

# Neural Networks
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor


from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [30]:
df = pd.read_csv('../../Data/zoo.data.csv', header = 0)

In [31]:
df.columns=['Name','hair','feathers','eggs','milk','airborne','aquatic', 'predator', 'toothed','backbone','breathes','venomous','fins','legs','tail','domestic','catsize','type']

In [32]:
# Print first few rows of data

,Name,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize,type
0,antelope,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1,1
1,bass,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,0,4
2,bear,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
3,boar,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1
4,buffalo,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1,1

In [35]:
print(df.shape)
df.describe()

(100, 18)

,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize,type
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00,100.000000,100.000000,100.00000,100.00000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000
mean,0.420000,0.200000,0.590000,0.400000,0.240000,0.360000,0.55,0.600000,0.820000,0.79000,0.08000,0.170000,2.830000,0.750000,0.130000,0.43000,2.850000
std,0.496045,0.402015,0.494311,0.492366,0.429235,0.482418,0.50,0.492366,0.386123,0.40936,0.27266,0.377525,2.040276,0.435194,0.337998,0.49757,2.105188
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,1.000000,1.00000,0.00000,0.000000,2.000000,0.750000,0.000000,0.00000,1.000000
50%,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.00,1.000000,1.000000,1.00000,0.00000,0.000000,3.000000,1.000000,0.000000,0.00000,2.000000
75%,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.00,1.000000,1.000000,1.00000,0.00000,0.000000,4.000000,1.000000,0.000000,1.00000,4.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00,1.000000,1.000000,1.00000,1.00000,1.000000,8.000000,1.000000,1.000000,1.00000,7.000000

In [37]:
# Create feature and target arrays

In [38]:
# One hot encode labels
from sklearn.preprocessing import OneHotEncoder 

encoded_X = OneHotEncoder().fit_transform(X).toarray()
print(encoded_X)

[[1. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]

In [39]:
# Split into Training & Testing Sets
X_train, X_test, y_train, y_test = train_test_split(encoded_X, y, test_size=0.30, random_state=123)

(70, 135)
(30, 135)

In [ ]:
# Print feature data

In [40]:
# Create Classifier Object
mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='relu', solver='adam', max_iter=250)

/Users/aodubela/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:568: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(

In [41]:
# Fit Classifier

<bound method MLPClassifier.fit of MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(8, 8, 8), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=250,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)>

In [ ]:
# Make Predictions
predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [42]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[29  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0]
 [ 0  0  4  0  0  0  0]
 [ 0  0  0  9  0  0  0]
 [ 0  0  0  0  0  0  2]
 [ 0  0  0  0  0  0  3]
 [ 0  0  0  0  0  0  9]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        29
           2       1.00      1.00      1.00        14
           3       1.00      1.00      1.00         4
           4       1.00      1.00      1.00         9
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         3
           7       0.64      1.00      0.78         9

    accuracy                           0.93        70
   macro avg       0.66      0.71      0.68        70
weighted avg       0.88      0.93      0.90        70

/Users/aodubela/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [43]:
print(confusion_matrix(y_test,predict_test))
print(classification_report(y_test,predict_test))

[[11  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0]
 [ 0  0  0  1  0  0  0]
 [ 0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  2]
 [ 0  0  0  0  0  0  5]
 [ 0  0  0  0  0  0  1]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00         6
           3       0.00      0.00      0.00         1
           4       0.80      1.00      0.89         4
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         5
           7       0.12      1.00      0.22         1

    accuracy                           0.73        30
   macro avg       0.42      0.57      0.44        30
weighted avg       0.68      0.73      0.69        30